version: 2.1
orbs:
  node: circleci/node@5.0.2
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  install-test:
    docker:
      - image: "circleci/node:10-browsers"
    steps:
      - node/install
      - checkout
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Front-End Test
          command: |
            npm run frontend:test

      
  debploy:
    docker:
      - image: "cimg/base:stable"
    steps:
      - aws-cli/setup
      - eb/setup
      - run:
          name: Deploy Frontend
          command: |
            npm run frontend:deploy
      - run:
          name: Deploy Backend
          command: |
            npm run backend:all


workflows:
  workflow:
    jobs:
      - install/test:
          filters:
            branches:
              only: master      
      - debploy:
         filters:
            branches:
              only: master